name: Check Single Line Change

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  check_single_line_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check single line change
        run: |
          # Get the number of lines changed in the pull request
          lines_changed=$(git diff --numstat ${{ github.event.before }} ${{ github.sha }} | awk '{print $1}')

          # Check if only one line is changed
          if [ $lines_changed -eq 1 ]; then
            echo "Success: Pull request changes only a single line."
          else
            echo "Error: Pull request changes more than one line."
            exit 1
          fi
